name: "Publish types package"
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn generate-types-package
      - run: yarn publish
        working-directory: ./types
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
